/**
 * OMP (Oh My Pi) hook injection.
 *
 * OMP has no settings.json-style shell-command hook list. It auto-loads
 * TypeScript *extensions* from the active agent dir — `~/.omp/agent/extensions`
 * by default (`--hook` is an alias of `--extension`, and the legacy
 * `hooks/pre|post` TS files feed the same runner). An extension default-exports
 * a factory that receives the ExtensionAPI; teamai subscribes to OMP's own
 * events and shells out to the same `teamai hook-dispatch` entry point every
 * other agent uses.
 *
 * Event mapping (OMP → teamai dispatch), chosen to mirror the Claude built-in
 * hook set (names verified against the OMP 18.2.5 ExtensionAPI):
 *   - `session_start`      → session-start  (report / sync / ack)
 *   - `session_stop`       → stop           (update / votes / contribute)
 *   - `before_agent_start` → prompt-submit  (track-slash / dashboard; carries `prompt`,
 *                                             and fires for print/RPC sessions too)
 *   - `tool_result`        → post-tool-use  (dashboard; wildcard only)
 *
 * The generated extension runs each dispatch for its side effects and never
 * blocks the agent: all shell errors are swallowed. `session_stop` IS awaited
 * by OMP before the main session settles — the dispatch carries its own
 * timeout, and the handler deliberately returns nothing: the `continue` /
 * `decision: "block"` fields of SessionStopEventResult would force a session
 * continuation and change OMP's own stop semantics.
 *
 * Only ONE copy is written, in the user agent dir. OMP also auto-loads project
 * extensions from `<cwd>/.omp/extensions`, and its dedup is absolute-path
 * based — two copies of this file would dispatch every event twice (the same
 * single-copy policy as the OpenCode plugin). Project gating happens inside
 * hook-dispatch, via the `cwd` forwarded on STDIN.
 */

import path from 'node:path';
import { writeIfChanged, pathExists, remove } from './utils/fs.js';
import { getUserHome } from './utils/home.js';
import { log } from './utils/logger.js';

/** Filename of the teamai-managed OMP extension. */
export const OMP_HOOK_FILE = 'teamai-hooks.ts';

/** Marker so `teamai uninstall` / `teamai hooks list` can recognize our generated file. */
const TEAMAI_MARKER = '[teamai]';

/**
 * Directory OMP auto-discovers user extensions in: the active agent dir's
 * `extensions/`. Only the default `~/.omp/agent/` layout is supported —
 * OMP profiles (`OMP_PROFILE` / `PI_CODING_AGENT_DIR` / `PI_CONFIG_DIR`)
 * relocate the agent dir and are out of scope.
 */
export function resolveOmpExtensionsDir(): string {
  return path.join(getUserHome(), '.omp', 'agent', 'extensions');
}

/**
 * Build the teamai OMP extension source.
 *
 * The extension subscribes to OMP events and shells out to `teamai
 * hook-dispatch <event> --tool omp`, feeding the same JSON payload on STDIN
 * that every other agent's hooks send (`cwd`, `tool_name`, `tool_input`,
 * `prompt`). It uses the Bun shell (`$`) — OMP runs extensions in-process
 * under Bun — with `.quiet().nothrow()` so a missing `teamai` binary or a
 * non-zero exit never surfaces as an error inside the agent session.
 *
 * OMP-specific bridges, mirroring the OpenCode plugin:
 *   - STDIN payload: hook-dispatch's track / track-slash handlers read
 *     `tool_name` / `tool_input` / `prompt` off STDIN, and the
 *     provider-config gate reads `cwd` to pick the project-scope config.
 *     The extension forwards `ctx.cwd` plus the per-event fields.
 *   - Recall attribution (#884): every event also carries the host's
 *     `session_id` (`ctx.sessionManager.getSessionId()`, a subagent's own
 *     session), and a subagent's events its `agent_id` / `agent_type` from
 *     `ctx.agent`, which only OMP >= 18.3.2 has: it is read only when present.
 *     `tool_result` also carries the tool's text output and a status from
 *     `isError`. A subagent's session file is `<parent>/<agent id>.jsonl`
 *     beside its parent's `<parent>.jsonl`, whose header names the parent
 *     session, so a subagent's first `tool_result` links its session to the
 *     parent's; OMP has no API for it. An in-memory session has no file and
 *     no link.
 *   - Tool naming: OMP passes lowercase tool ids (`bash`, `read`, …) and has
 *     no `Skill` / `TodoWrite` tool to map onto Claude's PascalCase matcher
 *     names, so there is no matcher-scoped pass — only the wildcard
 *     post-tool-use dispatch (the TodoWrite hint's STDOUT channel has no way
 *     back into an OMP session either).
 */
export function buildOmpExtensionSource(): string {
  return `// ${TEAMAI_MARKER} hooks extension — generated by teamai, do not edit by hand.
//
// Bridges OMP extension events to \`teamai hook-dispatch\`, mirroring the
// Claude built-in hook set. Feeds the same STDIN JSON payload other agents
// send (cwd / session_id / tool_name / tool_input / prompt, a subagent's
// agent_id / agent_type, and on post-tool-use the tool's text output and
// status) so the track / hint / recall handlers and project-scope gating work.
// Errors are swallowed; dispatches run for their side effects (status report /
// sync / update) and never block the agent.
//
// NOTE: OMP awaits session_stop before the session settles; this handler
// returns nothing on purpose — the \`continue\` / \`decision\` result fields
// would force a session continuation.

import { $ } from "bun";
import fs from "node:fs";
import path from "node:path";

/**
 * The session this handler serves (a subagent's own), and for a subagent its
 * identity. ctx.agent exists only from OMP 18.3.2, so each field is read
 * defensively.
 */
const sessionOf = (ctx) => {
  const fields = {};
  try {
    const id = ctx.sessionManager && ctx.sessionManager.getSessionId();
    if (typeof id === "string" && id) fields.session_id = id;
  } catch {}
  const agent = ctx.agent;
  if (agent && agent.kind === "sub" && typeof agent.id === "string" && agent.id) {
    fields.agent_id = agent.id;
    if (typeof agent.name === "string" && agent.name) fields.agent_type = agent.name;
  }
  return fields;
};

/**
 * The session a subagent's session was started from: its file is
 * <parent>/<agent id>.jsonl, and the first line of <parent>.jsonl is the
 * parent's session header. Undefined for any other session.
 */
const parentSessionOf = (ctx) => {
  try {
    const file = ctx.sessionManager && ctx.sessionManager.getSessionFile && ctx.sessionManager.getSessionFile();
    if (typeof file !== "string" || !file) return undefined;
    const fd = fs.openSync(\`\${path.dirname(file)}.jsonl\`, "r");
    try {
      const head = Buffer.alloc(65536);
      const size = fs.readSync(fd, head, 0, head.length, 0);
      const header = JSON.parse(head.toString("utf8", 0, size).split("\\n", 1)[0]);
      return header && header.type === "session" && typeof header.id === "string" && header.id ? header.id : undefined;
    } finally {
      fs.closeSync(fd);
    }
  } catch {
    return undefined;
  }
};

/** A tool result's text parts, joined; undefined when it has no content list. */
const textOf = (content) => Array.isArray(content)
  ? content.filter((part) => part && part.type === "text" && typeof part.text === "string").map((part) => part.text).join("\\n")
  : undefined;

/** @param {any} pi OMP ExtensionAPI */
export default function teamaiHooks(pi) {
  // Dispatch one hook event, forwarding a JSON payload on STDIN. \`payload\`
  // fields (cwd / tool_name / tool_input / prompt) match what
  // hook-dispatch's handlers read. No matcher pass: OMP's tool ids are
  // lowercase (bash / read / edit / write / ...) and it has no Skill /
  // TodoWrite tool to map onto Claude's PascalCase matchers.
  const dispatch = async (event, ctx, payload) => {
    try {
      const args = ["hook-dispatch", event, "--tool", "omp"];
      const stdin = JSON.stringify({ cwd: ctx.cwd, ...sessionOf(ctx), ...(payload || {}) });
      // Redirect the payload into STDIN via a Response (Bun shell can only
      // redirect Response/Buffer/Blob, not a bare string). .quiet() suppresses
      // output; .nothrow() keeps a non-zero exit (e.g. no teamai on PATH)
      // from throwing into the agent session.
      await $\`teamai \${args} < \${new Response(stdin)}\`.quiet().nothrow();
    } catch {
      // never block the agent
    }
  };

  pi.on("session_start", async (_event, ctx) => {
    await dispatch("session-start", ctx);
  });

  pi.on("session_stop", async (_event, ctx) => {
    await dispatch("stop", ctx);
  });

  pi.on("before_agent_start", async (event, ctx) => {
    await dispatch("prompt-submit", ctx, { prompt: event.prompt });
  });

  // Sessions already looked up: a session's parent never changes.
  const checked = new Set();

  // content is what the model saw; isError is set for a failed call,
  // including a bash command that exits non-zero.
  pi.on("tool_result", async (event, ctx) => {
    const payload = {
      tool_name: event.toolName,
      tool_input: event.input,
      tool_response: textOf(event.content),
      tool_status: event.isError === true ? "failure" : event.isError === false ? "success" : "unknown",
    };
    const child = sessionOf(ctx).session_id;
    if (child && !checked.has(child)) {
      checked.add(child);
      const parent = parentSessionOf(ctx);
      if (parent && parent !== child) payload.session_link = { child, parent };
    }
    await dispatch("post-tool-use", ctx, payload);
  });
}
`;
}

/**
 * Inject (or refresh) the teamai OMP extension. Idempotent — writes and
 * reports the extension file only when its content changes. The install gate
 * (~/.omp must exist) lives in the reconcile caller, so this never creates an
 * OMP config dir on its own.
 */
export async function injectOmpHooks(): Promise<void> {
  const file = path.join(resolveOmpExtensionsDir(), OMP_HOOK_FILE);
  if (await writeIfChanged(file, buildOmpExtensionSource())) {
    log.success(`Injected teamai OMP hook into ${file}`);
  } else {
    log.debug(`teamai OMP hook already up-to-date in ${file}`);
  }
}

/** Remove the teamai OMP extension if present. */
export async function removeOmpHooks(): Promise<void> {
  const file = path.join(resolveOmpExtensionsDir(), OMP_HOOK_FILE);
  if (await pathExists(file)) {
    await remove(file);
    log.success(`Removed teamai OMP hook from ${file}`);
  }
}
